DownloadCopy
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=run'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=user'
    ports:
      - '5432:5432'
